spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ngl143252
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    cache-period: 0
    mode: LEGACYHTML5
  template:
    cache: false
mybatis:
  typeAliasesPackage: org.spring.springboot.model
  mapperLocations: classpath:mapper/*.xml
